// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiuVBgDZ13d4R8G8Hs2IlVfP0DhXCZJ0',
    appId: '1:972618682797:web:1e188fade4e64bfc8cd124',
    messagingSenderId: '972618682797',
    projectId: 'my-personal-task-manager',
    authDomain: 'my-personal-task-manager.firebaseapp.com',
    storageBucket: 'my-personal-task-manager.appspot.com',
    measurementId: 'G-WBBRRRWH70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzHItwDzfcfcJglrJohY-lazTcipU8Q8',
    appId: '1:972618682797:android:b67878dba22692cb8cd124',
    messagingSenderId: '972618682797',
    projectId: 'my-personal-task-manager',
    storageBucket: 'my-personal-task-manager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA47OvEfSkilYl_yd-BopkYtEqhJXc6WK0',
    appId: '1:972618682797:ios:769de5823b18647b8cd124',
    messagingSenderId: '972618682797',
    projectId: 'my-personal-task-manager',
    storageBucket: 'my-personal-task-manager.appspot.com',
    iosBundleId: 'com.malibayram.myPersonalTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA47OvEfSkilYl_yd-BopkYtEqhJXc6WK0',
    appId: '1:972618682797:ios:1d67f49b0d6dea3e8cd124',
    messagingSenderId: '972618682797',
    projectId: 'my-personal-task-manager',
    storageBucket: 'my-personal-task-manager.appspot.com',
    iosBundleId: 'com.malibayram.myPersonalTaskManager.RunnerTests',
  );
}
